###
POST http://localhost:8080/api/v1/photo/upload?productId=4aa9a0ce-6b7d-4f32-b22b-0b6ed2f057ae
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo.jpg"

< /Users/azizbek/Desktop/photo.jpg


###
GET http://localhost:8080/api/v1/photo/get-by-product-id/4aa9a0ce-6b7d-4f32-b22b-0b6ed2f057ae

###
GET localhost:8080/api/v1/photo/by-product-id/d628769f-2e10-4805-b9a1-481d88a88047

###
GET localhost:8080/api/v1/photo/metadata/a130ac36-e822-492e-9ce0-2d94f49b64b4

###
GET localhost:8080/api/v1/photo/search?name=photo.jpg

###
POST localhost:8080/api/v1/photo/multi-upload?productId=4aa9a0ce-6b7d-4f32-b22b-0b6ed2f057ae
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="photo.jpg"

< /Users/azizbek/Desktop/photo.jpg

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="picture.png"

< /Users/azizbek/Desktop/picture.png