INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Ko‘chmas mulk', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Transport', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Ish', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Hayvonlar', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Uy va bog‘', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Elektr jihozlari', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Moda va stil', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Xobbi, dam olish, sport', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Bolalar olami', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Xizmatlar', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Biznes va uskunalar', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Ayirboshlash', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Telefonlar', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Kompyuterlar', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Foto / Video', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Maishiy texnika', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Go‘zallik va salomatlik', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Oziq-ovqat', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Ofis jihozlari', now(), now(), true);
INSERT INTO category (id, name, created_at, updated_at, visibility) VALUES (gen_random_uuid(), 'Kitoblar va jurnallar', now(), now(), true);
